# Generated by Django 5.0.4 on 2024-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='next_order',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='previous_order',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
