# Generated by Django 5.0.4 on 2024-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customers_next_order_customers_previous_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_address', models.TextField()),
                ('delivery_date', models.CharField(blank=True, max_length=50, null=True)),
                ('order_placed', models.DateTimeField(auto_now=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
