# Generated by Django 5.0.4 on 2024-04-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
