# Generated by Django 5.0.4 on 2024-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
