# Generated by Django 5.0.4 on 2024-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expense_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
